spring.application.name=SistemaMedico

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_medico
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false
